### ISSUE TITLE
Redesign the landing page using the new assest

### ISSUE THREAD

**Issue by steffeli** [javaBin/javazone-2019#36]

**Comment by alexander-svendsen** [comment]
Think this need a description or a picture of how it should look before anyone else can start on this

**Comment by lzpat** [comment]
https://vincentgarreau.com/particles.js/

bubble / particle effect

(The NASA effect is really cool)

MIT License :)

https://github.com/VincentGarreau/particles.js/blob/master/LICENSE.md

**Comment by steffeli** [comment]
> Think this need a description or a picture of how it should look before anyone else can start on this

Yeah I'll add a more detailed description today. Hopefully with a couple of sketches on how it may look like.

**Comment by steffeli** [comment]
> https://vincentgarreau.com/particles.js/
> 
> bubble / particle effect
> 
> (The NASA effect is really cool)
> 
> MIT License :)
> 
> https://github.com/VincentGarreau/particles.js/blob/master/LICENSE.md

Cool! Those are something we could use actually.
